name: PyTorch-1.8.1-GPU
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2
  - matplotlib=3.3.4
  - pip=21.1.1
  - python=3.8.10
  - pytorch=1.8.1
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - tqdm=4.59.0
  - pip:
    - wandb==0.10.32
    - tabulate==0.8.9
    - pytorch-lightning==1.3.6
    - torchmetrics==0.3.2
    - albumentations==1.0.0